# Generated by Django 5.2.17 on 2026-09-30 19:05

import content.images
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='שאלה')),
                ('answer', models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='תשובה')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='סדר')),
            ],
            options={
                'verbose_name': 'שאלה נפוצה',
                'verbose_name_plural': 'שאלות נפוצות',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='כותרת הלשונית')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='סדר')),
            ],
            options={
                'verbose_name': 'לשונית גלריה',
                'verbose_name_plural': 'לשוניות גלריה',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', validators=[content.images.validate_upload], verbose_name='תמונה')),
                ('alt_text', models.CharField(max_length=150, verbose_name='תיאור התמונה (לנגישות)')),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='סדר')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.gallerytab', verbose_name='לשונית')),
            ],
            options={
                'verbose_name': 'תמונה',
                'verbose_name_plural': 'תמונות',
                'ordering': ['order'],
            },
        ),
    ]
