# Generated by Django 5.2.17 on 2026-09-26 06:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='שם')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='תמונה')),
                ('text', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(1000)], verbose_name='המלצה')),
                ('stay_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='חודש שהות')),
                ('stay_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2020)], verbose_name='שנת שהות')),
                ('is_approved', models.BooleanField(default=False, verbose_name='מאושר לפרסום')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נשלח')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'המלצה',
                'verbose_name_plural': 'המלצות',
                'ordering': ['-stay_year', '-stay_month', '-created_at'],
            },
        ),
    ]
